### ISSUE TITLE
Are multi-kinect available on OPENNI2 SDK?

### ISSUE THREAD

**Issue by NAMCER** [occipital/OpenNI2#37]
hi I  m a student.
Are multi-kinect available on OPENNI2 SDK? 

plz reply the txt.
thanks

**Comment by mvm9289** [comment]
Hi,

Yes. Multi-Kinect is supported by OpenNI2. This is what I do when I
initialize OpenNI in order to handle multiple devices:

  // Initialize OpenNI  openni::Status res =
openni::OpenNI::initialize();  if (res != openni::STATUS_OK) {
KFB_LOG(ERROR_LVL) << "Unable to initialize KinectManager; "
            << openni::OpenNI::getExtendedError() << std::endl;
return;  }  initialized_ = true;  // Add available sensors
openni::Array<openni::DeviceInfo> deviceList;
openni::OpenNI::enumerateDevices(&deviceList);  for (int i = 0; i <
deviceList.getSize(); i++)  {    kfb::kinect::KinectDevice *dev    =
new kfb::kinect::KinectDevice(deviceList[i].getUri());
devices_[dev->getURI()].device    =
std::unique_ptr<kfb::kinect::KinectDevice>(dev);
devices_[dev->getURI()].connected = true;
dev->kfb::events::EventEmitter<kfb::kinect::KinectDeviceInitializedEvt>::attachListener(&evtManager_);
   dev->kfb::events::EventEmitter<kfb::kinect::KinectDeviceDestroyedEvt>::attachListener(&evtManager_);
 }  // Listen OpenNI events
openni::OpenNI::addDeviceConnectedListener(&evtManager_);
openni::OpenNI::addDeviceDisconnectedListener(&evtManager_);
openni::OpenNI::addDeviceStateChangedListener(&evtManager_);


My KinectDevice class basically manages an openni::Device and its
corresponding openni:VideoStreams: open/close device,
create/destroy/start/stop streams, etc.


Feel free to reach me out at mvm9289@gmail.com if you need extra help or
have questions.


Regards,

Miguel.

---------------------------------------------------------------------
* Email:                         mvm9289@gmail.com
* Phone number (Spain): +34 617 873 608
* Phone number (US):     +1 (408) 646-4533

**Comment by NAMCER** [comment]
To mvm9289
I really appreciate your favor, I will try your method.
I really wanna see result of your multikinect !! Thanx  :+1:

**Comment by ntisserand** [comment]
Thanks for the help, Miguel!

Closing the issue.

NAMCER, feel free to reopen it if needed.
