### ISSUE TITLE
ONI file format documentation

### ISSUE THREAD

**Issue by durka** [occipital/OpenNI2#54]
I'm sure that I am just looking in the wrong places, but I can't find any documentation at all on the ONI file format (created by the Recorder class). I'm wondering about things like timestamp accuracy, and how to get the images out later into a shareable format like PNG (or any format that I've heard of, really). Short of reading the code, is there any documentation on this?

**Comment by Windowsfreak** [comment]
It is actually possible to write a program that opens an ONI stream from a recorded file and read the stream, frame by frame due to playbackControl.setSpeed(-1). Then acquire the streams and pull the raw images (RGB, Depth) round-robin from the streams and save the framebuffers individually as PNG (RGB) / PNG 16bpp grayscale files. Additionally, from every VideoFrame the timestamp, frame id, fov and cropping information can be read.

However, I don't know how to create such an ONI-file, to feed the OpenNI library.

**Comment by jselikof** [comment]
Possibly helpful links here: [http://teslacore.blogspot.com/2015/09/swissknife-tool-for-oni-files.html](url) and here: https://groups.google.com/forum/embed/#!topic/openni-dev/KAXLEmCm-xI
