### ISSUE TITLE
GMCMode=0 does not disable function

### ISSUE THREAD

**Issue by akgoins** [occipital/OpenNI2#71]
Using the information from [issue 81](https://github.com/OpenNI/OpenNI2/issues/81) on the main repo, I was able to successfully disable GMCMode under Ubuntu 12.04 and using ROS Hydro.  However, under Ubuntu 14.04 and Indigo, setting GMCMode=0 does not appear to disable this function.  Also, it appears that the file PS1080.ini does not exist, and adding it does not seem to help.  I found two other .ini files (/etc/openni/GlobalDefaults.ini and /etc/openni2/OpenNI.ini) but adding this option to both files also fails to turn off this feature.  How can I turn off GMCMode?  Which .ini file is loaded by OpenNI2 under Ubuntu 14.04 and ROS Indigo?

**Comment by shaun-edwards** [comment]
I'm not sure what changed, but here is the solution (with some background):

In order to determine which file the driver was trying to load, I enabled verbose logging: `sudo gedit /etc/openni2/OpenNI.ini`.  I set the log level to verbose and enabled logging to the console as follows:
```
<snip>
[Log]
; 0 - Verbose; 1 - Info; 2 - Warning; 3 - Error. Default - None
Verbosity=0
LogToConsole=1
LogToFile=0
<snip>
```

After setting this, I brought up the openni driver in ros: `roslaunch openni2_launch openni2.launch
`.

The ROS output should now include Openni logging output.  It should looks similar to this:
```
<snip>
 721146 VERBOSE    Configuring module 'Depth' from section 'Depth' in file '/usr/lib/OpenNI2/Drivers/PS1080.ini'...
   722167 INFO       Module 'Depth' configuration was loaded from file.
   722574 INFO       Setting Depth.OutputFormat to 100...
   722584 INFO       Depth.OutputFormat value did not change.
   722588 INFO       Setting Depth.FPS to 30...
   722590 INFO       Depth.FPS value did not change.
   722594 INFO       Setting Depth.XRes to 640...
   722598 INFO       Property Depth.Resolution was changed to Custom.
<snip>
```

As indicated above, the Openni driver is looking for a config file in `/usr/lib/OpenNI2/Drivers/PS1080.ini`.  On my machine, this file did not exist.  I copied an existing file, with all values commented out, to this location.  I then disable GMCMode by setting: `GMCMode=0`

When running the ROS driver again, the following log messages indicate that `GMCMode` has been disabled:
```
<snip>
   709396 VERBOSE    Configuring module 'Depth' from section 'Depth' in file '/usr/lib/OpenNI2/Drivers/PS1080.ini'...
   709802 INFO       Setting Depth.GMCMode to 0...
   709815 INFO       Property Depth.GMCMode was changed to 0.
   709821 INFO       Depth.GMCMode was successfully set.
   709856 INFO       Module 'Depth' configuration was loaded from file.
<snip>
```

@akgoins, please verify this change has the intended effect on the 3D data it self.

**Comment by akgoins** [comment]
@shaun-edwards, yes this did turn off the GMCMode and remove the vertical lines.
